// Generated by tools/gen_analytics_contract.py. Do not edit.
export const ANALYTICS_SCHEMA_VERSION = 1 as const;
export const ANALYTICS_EVENTS = ["app_opened", "feature_viewed", "onboarding_step_completed", "deck_downloaded", "session_started", "session_completed", "session_abandoned", "game_result", "review_completed", "deck_maker_action", "purchase_flow", "setting_changed", "share_completed"] as const;
export const ANALYTICS_PROPERTIES = ["schema_version", "platform", "app_version", "build_number", "locale", "entry_point", "feature", "onboarding_step", "deck_source", "deck_category", "session_kind", "input_mode", "game_mode", "difficulty", "result", "reason", "duration_bucket", "item_count_bucket", "score_bucket", "action", "purchase_state", "setting", "value_bucket"] as const;
export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[number];
export type AnalyticsProperty = (typeof ANALYTICS_PROPERTIES)[number];
export const ALLOWED_PROPERTIES: Readonly<Record<AnalyticsEvent, ReadonlySet<AnalyticsProperty>>> = {
  app_opened: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "entry_point"]),
  feature_viewed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "feature"]),
  onboarding_step_completed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "onboarding_step"]),
  deck_downloaded: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "deck_source", "deck_category"]),
  session_started: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "session_kind", "deck_source", "input_mode", "game_mode", "difficulty"]),
  session_completed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "session_kind", "result", "duration_bucket", "item_count_bucket", "deck_source", "input_mode", "game_mode", "difficulty"]),
  session_abandoned: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "session_kind", "reason", "duration_bucket", "deck_source", "input_mode", "game_mode", "difficulty"]),
  game_result: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "game_mode", "difficulty", "result", "score_bucket", "input_mode", "deck_source"]),
  review_completed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "item_count_bucket", "result"]),
  deck_maker_action: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "action", "item_count_bucket", "deck_source"]),
  purchase_flow: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "purchase_state"]),
  setting_changed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "setting", "value_bucket"]),
  share_completed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "action", "game_mode"]),
};

export const REQUIRED_PROPERTIES: Readonly<Record<AnalyticsEvent, ReadonlySet<AnalyticsProperty>>> = {
  app_opened: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "entry_point"]),
  feature_viewed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "feature"]),
  onboarding_step_completed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "onboarding_step"]),
  deck_downloaded: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "deck_source", "deck_category"]),
  session_started: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "session_kind", "deck_source", "input_mode"]),
  session_completed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "session_kind", "result", "duration_bucket", "item_count_bucket"]),
  session_abandoned: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "session_kind", "reason", "duration_bucket"]),
  game_result: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "game_mode", "difficulty", "result", "score_bucket", "input_mode", "deck_source"]),
  review_completed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "item_count_bucket", "result"]),
  deck_maker_action: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "action"]),
  purchase_flow: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "purchase_state"]),
  setting_changed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "setting", "value_bucket"]),
  share_completed: new Set(["schema_version", "platform", "app_version", "build_number", "locale", "action"]),
};

export const ENUM_VALUES: Readonly<Partial<Record<AnalyticsProperty, ReadonlySet<string>>>> = {
  platform: new Set(["ios", "ipados", "android", "web"]),
  locale: new Set(["ja", "en", "ko", "other"]),
  entry_point: new Set(["cold_start", "foreground", "deep_link", "notification", "unknown"]),
  feature: new Set(["home", "discover", "practice", "game", "my_page", "settings", "deck_maker", "web_landing", "web_support"]),
  onboarding_step: new Set(["goal", "keyboard", "first_input", "hatch_1", "hatch_2", "hatch_3", "app_tour"]),
  deck_source: new Set(["bundled", "catalog", "imported", "created", "review", "daily", "curriculum", "unknown"]),
  deck_category: new Set(["beginner", "travel", "daily", "topik", "trend", "custom", "unknown"]),
  session_kind: new Set(["lesson", "free_practice", "review", "daily", "game"]),
  input_mode: new Set(["builtin", "builtin_korean_10key", "os_ime", "not_applicable"]),
  game_mode: new Set(["flow", "acid_rain", "choseong", "word_match", "dictation", "spacing", "not_applicable"]),
  difficulty: new Set(["beginner", "intermediate", "advanced", "custom", "not_applicable"]),
  result: new Set(["completed", "failed", "cancelled"]),
  reason: new Set(["user_closed", "background_timeout", "content_error", "unknown"]),
  duration_bucket: new Set(["under_1m", "1_to_3m", "3_to_7m", "over_7m"]),
  item_count_bucket: new Set(["1_to_3", "4_to_10", "11_to_30", "over_30"]),
  score_bucket: new Set(["0", "1_to_999", "1000_to_4999", "5000_plus"]),
  action: new Set(["created", "edited", "copied", "imported", "exported", "deleted", "shared", "saved_image"]),
  purchase_state: new Set(["viewed", "started", "pending", "completed", "cancelled", "failed", "restored"]),
  setting: new Set(["language", "theme", "input_mode", "practice_display", "sound", "analytics_consent", "diagnostics_consent"]),
  value_bucket: new Set(["enabled", "disabled", "ja", "en", "ko", "light", "dark", "builtin", "os_ime", "learning", "focus", "other"]),
};

export function accepts(event: AnalyticsEvent, properties: Record<string, unknown>): boolean {
  const allowed = ALLOWED_PROPERTIES[event];
  const keys = Object.keys(properties);
  if (![...REQUIRED_PROPERTIES[event]].every((key) => key in properties) ||
      !keys.every((key) => allowed.has(key as AnalyticsProperty)) ||
      properties.schema_version !== ANALYTICS_SCHEMA_VERSION ||
      typeof properties.app_version !== "string" ||
      typeof properties.build_number !== "string") return false;
  return Object.entries(ENUM_VALUES).every(([property, values]) =>
    !(property in properties) ||
    (typeof properties[property] === "string" && values?.has(properties[property] as string)),
  );
}
