// Generated by tools/gen_analytics_contract.py. Do not edit.
import Foundation

enum AnalyticsEvent: String, CaseIterable {
  case appOpened = "app_opened"
  case featureViewed = "feature_viewed"
  case onboardingStepCompleted = "onboarding_step_completed"
  case deckDownloaded = "deck_downloaded"
  case sessionStarted = "session_started"
  case sessionCompleted = "session_completed"
  case sessionAbandoned = "session_abandoned"
  case gameResult = "game_result"
  case reviewCompleted = "review_completed"
  case deckMakerAction = "deck_maker_action"
  case purchaseFlow = "purchase_flow"
  case settingChanged = "setting_changed"
  case shareCompleted = "share_completed"
}

enum AnalyticsProperty: String, CaseIterable {
  case schemaVersion = "schema_version"
  case platform = "platform"
  case appVersion = "app_version"
  case buildNumber = "build_number"
  case locale = "locale"
  case entryPoint = "entry_point"
  case feature = "feature"
  case onboardingStep = "onboarding_step"
  case deckSource = "deck_source"
  case deckCategory = "deck_category"
  case sessionKind = "session_kind"
  case inputMode = "input_mode"
  case gameMode = "game_mode"
  case difficulty = "difficulty"
  case result = "result"
  case reason = "reason"
  case durationBucket = "duration_bucket"
  case itemCountBucket = "item_count_bucket"
  case scoreBucket = "score_bucket"
  case action = "action"
  case purchaseState = "purchase_state"
  case setting = "setting"
  case valueBucket = "value_bucket"
}

enum AnalyticsContract {
  static let schemaVersion = 1
  static let allowedProperties: [AnalyticsEvent: Set<AnalyticsProperty>] = [
    .appOpened: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .entryPoint],
    .featureViewed: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .feature],
    .onboardingStepCompleted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .onboardingStep],
    .deckDownloaded: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .deckSource, .deckCategory],
    .sessionStarted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .sessionKind, .deckSource, .inputMode, .gameMode, .difficulty],
    .sessionCompleted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .sessionKind, .result, .durationBucket, .itemCountBucket, .deckSource, .inputMode, .gameMode, .difficulty],
    .sessionAbandoned: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .sessionKind, .reason, .durationBucket, .deckSource, .inputMode, .gameMode, .difficulty],
    .gameResult: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .gameMode, .difficulty, .result, .scoreBucket, .inputMode, .deckSource],
    .reviewCompleted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .itemCountBucket, .result],
    .deckMakerAction: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .action, .itemCountBucket, .deckSource],
    .purchaseFlow: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .purchaseState],
    .settingChanged: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .setting, .valueBucket],
    .shareCompleted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .action, .gameMode],
  ]

  static let requiredProperties: [AnalyticsEvent: Set<AnalyticsProperty>] = [
    .appOpened: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .entryPoint],
    .featureViewed: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .feature],
    .onboardingStepCompleted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .onboardingStep],
    .deckDownloaded: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .deckSource, .deckCategory],
    .sessionStarted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .sessionKind, .deckSource, .inputMode],
    .sessionCompleted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .sessionKind, .result, .durationBucket, .itemCountBucket],
    .sessionAbandoned: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .sessionKind, .reason, .durationBucket],
    .gameResult: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .gameMode, .difficulty, .result, .scoreBucket, .inputMode, .deckSource],
    .reviewCompleted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .itemCountBucket, .result],
    .deckMakerAction: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .action],
    .purchaseFlow: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .purchaseState],
    .settingChanged: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .setting, .valueBucket],
    .shareCompleted: [.schemaVersion, .platform, .appVersion, .buildNumber, .locale, .action],
  ]

  static let enumValues: [AnalyticsProperty: Set<String>] = [
    .platform: ["ios", "ipados", "android", "web"],
    .locale: ["ja", "en", "ko", "other"],
    .entryPoint: ["cold_start", "foreground", "deep_link", "notification", "unknown"],
    .feature: ["home", "discover", "practice", "game", "my_page", "settings", "deck_maker", "web_landing", "web_support"],
    .onboardingStep: ["goal", "keyboard", "first_input", "hatch_1", "hatch_2", "hatch_3", "app_tour"],
    .deckSource: ["bundled", "catalog", "imported", "created", "review", "daily", "curriculum", "unknown"],
    .deckCategory: ["beginner", "travel", "daily", "topik", "trend", "custom", "unknown"],
    .sessionKind: ["lesson", "free_practice", "review", "daily", "game"],
    .inputMode: ["builtin", "os_ime", "not_applicable"],
    .gameMode: ["flow", "acid_rain", "choseong", "word_match", "dictation", "spacing", "not_applicable"],
    .difficulty: ["beginner", "intermediate", "advanced", "custom", "not_applicable"],
    .result: ["completed", "failed", "cancelled"],
    .reason: ["user_closed", "background_timeout", "content_error", "unknown"],
    .durationBucket: ["under_1m", "1_to_3m", "3_to_7m", "over_7m"],
    .itemCountBucket: ["1_to_3", "4_to_10", "11_to_30", "over_30"],
    .scoreBucket: ["0", "1_to_999", "1000_to_4999", "5000_plus"],
    .action: ["created", "edited", "copied", "imported", "exported", "deleted", "shared", "saved_image"],
    .purchaseState: ["viewed", "started", "pending", "completed", "cancelled", "failed", "restored"],
    .setting: ["language", "theme", "input_mode", "practice_display", "sound", "analytics_consent", "diagnostics_consent"],
    .valueBucket: ["enabled", "disabled", "ja", "en", "ko", "light", "dark", "builtin", "os_ime", "learning", "focus", "other"],
  ]

  static func accepts(event: AnalyticsEvent, properties: [AnalyticsProperty: Any]) -> Bool {
    guard let allowed = allowedProperties[event], let required = requiredProperties[event] else { return false }
    let keys = Set(properties.keys)
    guard required.isSubset(of: keys), keys.isSubset(of: allowed) else { return false }
    guard properties[.schemaVersion] as? Int == schemaVersion,
      properties[.appVersion] is String, properties[.buildNumber] is String
    else { return false }
    for (property, values) in enumValues where properties[property] != nil {
      guard let value = properties[property] as? String, values.contains(value) else { return false }
    }
    return true
  }
}
