// Generated by tools/gen_analytics_contract.py. Do not edit.
package app.piyokey.core.analytics

enum class AnalyticsEvent(val wireName: String) {
  APP_OPENED("app_opened"),
  FEATURE_VIEWED("feature_viewed"),
  ONBOARDING_STEP_COMPLETED("onboarding_step_completed"),
  DECK_DOWNLOADED("deck_downloaded"),
  SESSION_STARTED("session_started"),
  SESSION_COMPLETED("session_completed"),
  SESSION_ABANDONED("session_abandoned"),
  GAME_RESULT("game_result"),
  REVIEW_COMPLETED("review_completed"),
  DECK_MAKER_ACTION("deck_maker_action"),
  PURCHASE_FLOW("purchase_flow"),
  SETTING_CHANGED("setting_changed"),
  SHARE_COMPLETED("share_completed"),
}

enum class AnalyticsProperty(val wireName: String) {
  SCHEMA_VERSION("schema_version"),
  PLATFORM("platform"),
  APP_VERSION("app_version"),
  BUILD_NUMBER("build_number"),
  LOCALE("locale"),
  ENTRY_POINT("entry_point"),
  FEATURE("feature"),
  ONBOARDING_STEP("onboarding_step"),
  DECK_SOURCE("deck_source"),
  DECK_CATEGORY("deck_category"),
  SESSION_KIND("session_kind"),
  INPUT_MODE("input_mode"),
  GAME_MODE("game_mode"),
  DIFFICULTY("difficulty"),
  RESULT("result"),
  REASON("reason"),
  DURATION_BUCKET("duration_bucket"),
  ITEM_COUNT_BUCKET("item_count_bucket"),
  SCORE_BUCKET("score_bucket"),
  ACTION("action"),
  PURCHASE_STATE("purchase_state"),
  SETTING("setting"),
  VALUE_BUCKET("value_bucket"),
}

object AnalyticsContract {
  const val SCHEMA_VERSION: Int = 1
  val allowedProperties: Map<AnalyticsEvent, Set<AnalyticsProperty>> = mapOf(
    AnalyticsEvent.APP_OPENED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ENTRY_POINT),
    AnalyticsEvent.FEATURE_VIEWED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.FEATURE),
    AnalyticsEvent.ONBOARDING_STEP_COMPLETED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ONBOARDING_STEP),
    AnalyticsEvent.DECK_DOWNLOADED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.DECK_SOURCE, AnalyticsProperty.DECK_CATEGORY),
    AnalyticsEvent.SESSION_STARTED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.SESSION_KIND, AnalyticsProperty.DECK_SOURCE, AnalyticsProperty.INPUT_MODE, AnalyticsProperty.GAME_MODE, AnalyticsProperty.DIFFICULTY),
    AnalyticsEvent.SESSION_COMPLETED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.SESSION_KIND, AnalyticsProperty.RESULT, AnalyticsProperty.DURATION_BUCKET, AnalyticsProperty.ITEM_COUNT_BUCKET, AnalyticsProperty.DECK_SOURCE, AnalyticsProperty.INPUT_MODE, AnalyticsProperty.GAME_MODE, AnalyticsProperty.DIFFICULTY),
    AnalyticsEvent.SESSION_ABANDONED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.SESSION_KIND, AnalyticsProperty.REASON, AnalyticsProperty.DURATION_BUCKET, AnalyticsProperty.DECK_SOURCE, AnalyticsProperty.INPUT_MODE, AnalyticsProperty.GAME_MODE, AnalyticsProperty.DIFFICULTY),
    AnalyticsEvent.GAME_RESULT to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.GAME_MODE, AnalyticsProperty.DIFFICULTY, AnalyticsProperty.RESULT, AnalyticsProperty.SCORE_BUCKET, AnalyticsProperty.INPUT_MODE, AnalyticsProperty.DECK_SOURCE),
    AnalyticsEvent.REVIEW_COMPLETED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ITEM_COUNT_BUCKET, AnalyticsProperty.RESULT),
    AnalyticsEvent.DECK_MAKER_ACTION to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ACTION, AnalyticsProperty.ITEM_COUNT_BUCKET, AnalyticsProperty.DECK_SOURCE),
    AnalyticsEvent.PURCHASE_FLOW to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.PURCHASE_STATE),
    AnalyticsEvent.SETTING_CHANGED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.SETTING, AnalyticsProperty.VALUE_BUCKET),
    AnalyticsEvent.SHARE_COMPLETED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ACTION, AnalyticsProperty.GAME_MODE),
  )

  val requiredProperties: Map<AnalyticsEvent, Set<AnalyticsProperty>> = mapOf(
    AnalyticsEvent.APP_OPENED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ENTRY_POINT),
    AnalyticsEvent.FEATURE_VIEWED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.FEATURE),
    AnalyticsEvent.ONBOARDING_STEP_COMPLETED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ONBOARDING_STEP),
    AnalyticsEvent.DECK_DOWNLOADED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.DECK_SOURCE, AnalyticsProperty.DECK_CATEGORY),
    AnalyticsEvent.SESSION_STARTED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.SESSION_KIND, AnalyticsProperty.DECK_SOURCE, AnalyticsProperty.INPUT_MODE),
    AnalyticsEvent.SESSION_COMPLETED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.SESSION_KIND, AnalyticsProperty.RESULT, AnalyticsProperty.DURATION_BUCKET, AnalyticsProperty.ITEM_COUNT_BUCKET),
    AnalyticsEvent.SESSION_ABANDONED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.SESSION_KIND, AnalyticsProperty.REASON, AnalyticsProperty.DURATION_BUCKET),
    AnalyticsEvent.GAME_RESULT to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.GAME_MODE, AnalyticsProperty.DIFFICULTY, AnalyticsProperty.RESULT, AnalyticsProperty.SCORE_BUCKET, AnalyticsProperty.INPUT_MODE, AnalyticsProperty.DECK_SOURCE),
    AnalyticsEvent.REVIEW_COMPLETED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ITEM_COUNT_BUCKET, AnalyticsProperty.RESULT),
    AnalyticsEvent.DECK_MAKER_ACTION to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ACTION),
    AnalyticsEvent.PURCHASE_FLOW to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.PURCHASE_STATE),
    AnalyticsEvent.SETTING_CHANGED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.SETTING, AnalyticsProperty.VALUE_BUCKET),
    AnalyticsEvent.SHARE_COMPLETED to setOf(AnalyticsProperty.SCHEMA_VERSION, AnalyticsProperty.PLATFORM, AnalyticsProperty.APP_VERSION, AnalyticsProperty.BUILD_NUMBER, AnalyticsProperty.LOCALE, AnalyticsProperty.ACTION),
  )

  val enumValues: Map<AnalyticsProperty, Set<String>> = mapOf(
    AnalyticsProperty.PLATFORM to setOf("ios", "ipados", "android", "web"),
    AnalyticsProperty.LOCALE to setOf("ja", "en", "ko", "es", "de", "fr", "other"),
    AnalyticsProperty.ENTRY_POINT to setOf("cold_start", "foreground", "deep_link", "notification", "unknown"),
    AnalyticsProperty.FEATURE to setOf("home", "discover", "practice", "game", "my_page", "settings", "deck_maker", "web_landing", "web_support"),
    AnalyticsProperty.ONBOARDING_STEP to setOf("goal", "keyboard", "first_input", "hatch_1", "hatch_2", "hatch_3", "app_tour"),
    AnalyticsProperty.DECK_SOURCE to setOf("bundled", "catalog", "imported", "created", "review", "daily", "curriculum", "unknown"),
    AnalyticsProperty.DECK_CATEGORY to setOf("beginner", "travel", "daily", "topik", "trend", "custom", "unknown"),
    AnalyticsProperty.SESSION_KIND to setOf("lesson", "free_practice", "review", "daily", "game"),
    AnalyticsProperty.INPUT_MODE to setOf("builtin", "builtin_korean_10key", "os_ime", "not_applicable"),
    AnalyticsProperty.GAME_MODE to setOf("flow", "acid_rain", "choseong", "word_match", "dictation", "spacing", "not_applicable"),
    AnalyticsProperty.DIFFICULTY to setOf("beginner", "intermediate", "advanced", "custom", "not_applicable"),
    AnalyticsProperty.RESULT to setOf("completed", "failed", "cancelled"),
    AnalyticsProperty.REASON to setOf("user_closed", "background_timeout", "content_error", "unknown"),
    AnalyticsProperty.DURATION_BUCKET to setOf("under_1m", "1_to_3m", "3_to_7m", "over_7m"),
    AnalyticsProperty.ITEM_COUNT_BUCKET to setOf("1_to_3", "4_to_10", "11_to_30", "over_30"),
    AnalyticsProperty.SCORE_BUCKET to setOf("0", "1_to_999", "1000_to_4999", "5000_plus"),
    AnalyticsProperty.ACTION to setOf("created", "edited", "copied", "imported", "exported", "deleted", "shared", "saved_image"),
    AnalyticsProperty.PURCHASE_STATE to setOf("viewed", "started", "pending", "completed", "cancelled", "failed", "restored"),
    AnalyticsProperty.SETTING to setOf("language", "theme", "input_mode", "practice_display", "sound", "analytics_consent", "diagnostics_consent"),
    AnalyticsProperty.VALUE_BUCKET to setOf("enabled", "disabled", "ja", "en", "ko", "es", "de", "fr", "light", "dark", "builtin", "os_ime", "learning", "focus", "other"),
  )

  fun accepts(event: AnalyticsEvent, properties: Map<AnalyticsProperty, Any>): Boolean {
    val keys = properties.keys
    if (!keys.containsAll(requiredProperties.getValue(event)) ||
      !allowedProperties.getValue(event).containsAll(keys) ||
      properties[AnalyticsProperty.SCHEMA_VERSION] != SCHEMA_VERSION ||
      properties[AnalyticsProperty.APP_VERSION] !is String ||
      properties[AnalyticsProperty.BUILD_NUMBER] !is String
    ) return false
    return enumValues.all { (property, values) ->
      properties[property]?.let { it is String && it in values } ?: true
    }
  }
}
