#!/usr/bin/env python3
"""Generate the platform analytics allowlist from shared/analytics/events.json."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared/analytics/events.json"
OUTPUTS = {
    "swift": ROOT / "ios/Hanco/Hanco/Core/Analytics/AnalyticsContract.generated.swift",
    "kotlin": ROOT / "android/core/analytics/src/main/kotlin/app/piyokey/core/analytics/AnalyticsContract.generated.kt",
    "typescript": ROOT / "web/analytics/src/contract.generated.ts",
}


def camel(value: str, upper: bool = False) -> str:
    parts = value.split("_")
    result = parts[0] + "".join(part.title() for part in parts[1:])
    return result[:1].upper() + result[1:] if upper else result


def load_contract() -> dict:
    contract = json.loads(SOURCE.read_text(encoding="utf-8"))
    properties = set(contract["properties"])
    forbidden = set(contract["forbidden_properties"])
    if properties & forbidden:
        raise ValueError(f"Forbidden properties are allowlisted: {sorted(properties & forbidden)}")
    common = set(contract["common_required"])
    if not common <= properties:
        raise ValueError("Unknown common property")
    for event, definition in contract["events"].items():
        if not re.fullmatch(r"[a-z][a-z0-9_]*", event):
            raise ValueError(f"Invalid event name: {event}")
        referenced = set(definition.get("required", [])) | set(definition.get("optional", []))
        if not referenced <= properties:
            raise ValueError(f"{event} references unknown properties: {sorted(referenced - properties)}")
    return contract


def event_map(contract: dict) -> dict[str, list[str]]:
    common = contract["common_required"]
    return {
        event: list(dict.fromkeys(common + definition.get("required", []) + definition.get("optional", [])))
        for event, definition in contract["events"].items()
    }


def required_map(contract: dict) -> dict[str, list[str]]:
    common = contract["common_required"]
    return {
        event: list(dict.fromkeys(common + definition.get("required", [])))
        for event, definition in contract["events"].items()
    }


def enum_map(contract: dict) -> dict[str, list[str]]:
    return {
        name: definition["values"]
        for name, definition in contract["properties"].items()
        if definition["type"] == "enum"
    }


def render_swift(contract: dict) -> str:
    events = contract["events"]
    properties = contract["properties"]
    allowed = event_map(contract)
    required = required_map(contract)
    enum_values = enum_map(contract)
    lines = [
        "// Generated by tools/gen_analytics_contract.py. Do not edit.",
        "import Foundation",
        "",
        "enum AnalyticsEvent: String, CaseIterable {",
        *[f'  case {camel(name)} = "{name}"' for name in events],
        "}",
        "",
        "enum AnalyticsProperty: String, CaseIterable {",
        *[f'  case {camel(name)} = "{name}"' for name in properties],
        "}",
        "",
        "enum AnalyticsContract {",
        f"  static let schemaVersion = {contract['schema_version']}",
        "  static let allowedProperties: [AnalyticsEvent: Set<AnalyticsProperty>] = [",
    ]
    for event, names in allowed.items():
        values = ", ".join(f".{camel(name)}" for name in names)
        lines.append(f"    .{camel(event)}: [{values}],")
    lines += [
        "  ]",
        "",
        "  static let requiredProperties: [AnalyticsEvent: Set<AnalyticsProperty>] = [",
    ]
    for event, names in required.items():
        values = ", ".join(f".{camel(name)}" for name in names)
        lines.append(f"    .{camel(event)}: [{values}],")
    lines += [
        "  ]",
        "",
        "  static let enumValues: [AnalyticsProperty: Set<String>] = [",
    ]
    for name, values in enum_values.items():
        rendered_values = ", ".join(f'"{value}"' for value in values)
        lines.append(f"    .{camel(name)}: [{rendered_values}],")
    lines += [
        "  ]",
        "",
        "  static func accepts(event: AnalyticsEvent, properties: [AnalyticsProperty: Any]) -> Bool {",
        "    guard let allowed = allowedProperties[event], let required = requiredProperties[event] else { return false }",
        "    let keys = Set(properties.keys)",
        "    guard required.isSubset(of: keys), keys.isSubset(of: allowed) else { return false }",
        "    guard properties[.schemaVersion] as? Int == schemaVersion,",
        "      properties[.appVersion] is String, properties[.buildNumber] is String",
        "    else { return false }",
        "    for (property, values) in enumValues where properties[property] != nil {",
        "      guard let value = properties[property] as? String, values.contains(value) else { return false }",
        "    }",
        "    return true",
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_kotlin(contract: dict) -> str:
    events = contract["events"]
    properties = contract["properties"]
    allowed = event_map(contract)
    required = required_map(contract)
    enum_values = enum_map(contract)
    lines = [
        "// Generated by tools/gen_analytics_contract.py. Do not edit.",
        "package app.piyokey.core.analytics",
        "",
        "enum class AnalyticsEvent(val wireName: String) {",
        *[f'  {name.upper()}("{name}"),' for name in events],
        "}",
        "",
        "enum class AnalyticsProperty(val wireName: String) {",
        *[f'  {name.upper()}("{name}"),' for name in properties],
        "}",
        "",
        "object AnalyticsContract {",
        f"  const val SCHEMA_VERSION: Int = {contract['schema_version']}",
        "  val allowedProperties: Map<AnalyticsEvent, Set<AnalyticsProperty>> = mapOf(",
    ]
    for event, names in allowed.items():
        values = ", ".join(f"AnalyticsProperty.{name.upper()}" for name in names)
        lines.append(f"    AnalyticsEvent.{event.upper()} to setOf({values}),")
    lines += [
        "  )",
        "",
        "  val requiredProperties: Map<AnalyticsEvent, Set<AnalyticsProperty>> = mapOf(",
    ]
    for event, names in required.items():
        values = ", ".join(f"AnalyticsProperty.{name.upper()}" for name in names)
        lines.append(f"    AnalyticsEvent.{event.upper()} to setOf({values}),")
    lines += [
        "  )",
        "",
        "  val enumValues: Map<AnalyticsProperty, Set<String>> = mapOf(",
    ]
    for name, values in enum_values.items():
        rendered_values = ", ".join(f'"{value}"' for value in values)
        lines.append(f"    AnalyticsProperty.{name.upper()} to setOf({rendered_values}),")
    lines += [
        "  )",
        "",
        "  fun accepts(event: AnalyticsEvent, properties: Map<AnalyticsProperty, Any>): Boolean {",
        "    val keys = properties.keys",
        "    if (!keys.containsAll(requiredProperties.getValue(event)) ||",
        "      !allowedProperties.getValue(event).containsAll(keys) ||",
        "      properties[AnalyticsProperty.SCHEMA_VERSION] != SCHEMA_VERSION ||",
        "      properties[AnalyticsProperty.APP_VERSION] !is String ||",
        "      properties[AnalyticsProperty.BUILD_NUMBER] !is String",
        "    ) return false",
        "    return enumValues.all { (property, values) ->",
        "      properties[property]?.let { it is String && it in values } ?: true",
        "    }",
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_typescript(contract: dict) -> str:
    events = list(contract["events"])
    properties = list(contract["properties"])
    allowed = event_map(contract)
    required = required_map(contract)
    enum_values = enum_map(contract)
    lines = [
        "// Generated by tools/gen_analytics_contract.py. Do not edit.",
        f"export const ANALYTICS_SCHEMA_VERSION = {contract['schema_version']} as const;",
        f"export const ANALYTICS_EVENTS = {json.dumps(events)} as const;",
        f"export const ANALYTICS_PROPERTIES = {json.dumps(properties)} as const;",
        "export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[number];",
        "export type AnalyticsProperty = (typeof ANALYTICS_PROPERTIES)[number];",
        "export const ALLOWED_PROPERTIES: Readonly<Record<AnalyticsEvent, ReadonlySet<AnalyticsProperty>>> = {",
    ]
    for event, names in allowed.items():
        values = json.dumps(names)
        lines.append(f"  {event}: new Set({values}),")
    lines += [
        "};",
        "",
        "export const REQUIRED_PROPERTIES: Readonly<Record<AnalyticsEvent, ReadonlySet<AnalyticsProperty>>> = {",
    ]
    for event, names in required.items():
        values = json.dumps(names)
        lines.append(f"  {event}: new Set({values}),")
    lines += [
        "};",
        "",
        "export const ENUM_VALUES: Readonly<Partial<Record<AnalyticsProperty, ReadonlySet<string>>>> = {",
    ]
    for name, values in enum_values.items():
        lines.append(f"  {name}: new Set({json.dumps(values)}),")
    lines += [
        "};",
        "",
        "export function accepts(event: AnalyticsEvent, properties: Record<string, unknown>): boolean {",
        "  const allowed = ALLOWED_PROPERTIES[event];",
        "  const keys = Object.keys(properties);",
        "  if (![...REQUIRED_PROPERTIES[event]].every((key) => key in properties) ||",
        "      !keys.every((key) => allowed.has(key as AnalyticsProperty)) ||",
        "      properties.schema_version !== ANALYTICS_SCHEMA_VERSION ||",
        "      typeof properties.app_version !== \"string\" ||",
        "      typeof properties.build_number !== \"string\") return false;",
        "  return Object.entries(ENUM_VALUES).every(([property, values]) =>",
        "    !(property in properties) ||",
        "    (typeof properties[property] === \"string\" && values?.has(properties[property] as string)),",
        "  );",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = load_contract()
    rendered = {
        "swift": render_swift(contract),
        "kotlin": render_kotlin(contract),
        "typescript": render_typescript(contract),
    }
    stale: list[str] = []
    for key, path in OUTPUTS.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != rendered[key]:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(rendered[key], encoding="utf-8")
    if stale:
        raise SystemExit("Stale analytics generated files: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
