#!/usr/bin/env python3
"""Generate Android string resources from the iOS localization source of truth.

iOS `Localizable.strings`/`.stringsdict` (ja, en, es, de, fr) and the
locale-neutral `KoreanLearningContent.strings` are converted into
`android/app/src/main/res/values*/strings_generated.xml`. Keys keep their iOS
meaning; `.` and `-` become `_` so `practice.title` is `R.string.practice_title`.

Run `python3 tools/gen_android_strings.py` after changing iOS strings and commit
the output. `--check` fails when the committed output is stale.
"""
from __future__ import annotations

import argparse
import plistlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IOS_RESOURCES = ROOT / "ios/Hanco/Hanco/Resources"
ANDROID_RES = ROOT / "android/app/src/main/res"
UI_LOCALES = ("en", "ja", "es", "de", "fr")
DEFAULT_LOCALE = "en"
OUTPUT_NAME = "strings_generated.xml"
LEARNING_OUTPUT_NAME = "learning_content_generated.xml"
LEARNING_PREFIX = "ko_"
OVERRIDES = ROOT / "tools/android_string_overrides.json"

ENTRY = re.compile(r'^"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)";', re.M)
SPECIFIER = re.compile(r"%(?:(\d+)\$)?([#0\-+ ]*\d*(?:\.\d+)?)(@|d|ld|lld|i|u|f|s|%)")


def android_name(key: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_]", "_", key)
    if not re.match(r"[A-Za-z]", name):
        name = "k_" + name
    return name


def unescape_ios(value: str) -> str:
    out = []
    i = 0
    while i < len(value):
        char = value[i]
        if char == "\\" and i + 1 < len(value):
            nxt = value[i + 1]
            out.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\", "'": "'"}.get(nxt, nxt))
            i += 2
            continue
        out.append(char)
        i += 1
    return "".join(out)


def parse_strings(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    return {key: unescape_ios(value) for key, value in ENTRY.findall(text)}


def convert_format(value: str) -> tuple[str, bool]:
    """Convert iOS printf specifiers to Android ones; returns (value, has_args)."""
    matches = [m for m in SPECIFIER.finditer(value) if m.group(3) != "%"]
    positional = len(matches) > 1
    counter = 0

    def replace(match: re.Match[str]) -> str:
        nonlocal counter
        index, flags, conversion = match.groups()
        if conversion == "%":
            return "%%"
        counter += 1
        position = index or (str(counter) if positional else None)
        kind = {"@": "s", "ld": "d", "lld": "d", "i": "d", "u": "d"}.get(conversion, conversion)
        prefix = f"%{position}$" if position else "%"
        return f"{prefix}{flags}{kind}"

    converted = SPECIFIER.sub(replace, value)
    if not matches:
        # A string without arguments is not passed through a formatter.
        converted = value
    return converted, bool(matches)


def escape_android(value: str) -> str:
    value = value.replace("\\", "\\\\")
    value = value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    value = value.replace('"', '\\"').replace("'", "\\'")
    value = value.replace("\n", "\\n").replace("\t", "\\t")
    if value.startswith(("@", "?")):
        value = "\\" + value
    return value


def render_strings(entries: dict[str, str], plurals: dict[str, dict], translatable: bool = True) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tools/gen_android_strings.py from iOS resources. Do not edit. -->",
        '<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation,UnusedResources,Typos">',
    ]
    for key in sorted(entries):
        value, has_args = convert_format(entries[key])
        attrs = f' name="{android_name(key)}"'
        if not translatable:
            attrs += ' translatable="false"'
        if not has_args and "%" in value:
            attrs += ' formatted="false"'
        lines.append(f"  <string{attrs}>{escape_android(value)}</string>")
    for key in sorted(plurals):
        lines.append(f'  <plurals name="{android_name(key)}">')
        for quantity in ("zero", "one", "two", "few", "many", "other"):
            if quantity in plurals[key]:
                value, _ = convert_format(plurals[key][quantity])
                lines.append(f'    <item quantity="{quantity}">{escape_android(value)}</item>')
        lines.append("  </plurals>")
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def load_plurals(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    with path.open("rb") as stream:
        document = plistlib.load(stream)
    result: dict[str, dict] = {}
    for key, entry in document.items():
        variables = {k: v for k, v in entry.items() if isinstance(v, dict)}
        if len(variables) != 1:
            raise SystemExit(f"Unsupported stringsdict entry with {len(variables)} variables: {key}")
        rule = next(iter(variables.values()))
        result[key] = {q: rule[q] for q in ("zero", "one", "two", "few", "many", "other") if q in rule}
    return result


def load_overrides() -> dict[str, dict[str, str]]:
    import json

    document = json.loads(OVERRIDES.read_text(encoding="utf-8"))
    return {locale: values for locale, values in document.items() if not locale.startswith("_")}


def render_all() -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    overrides = load_overrides()
    override_keys = {key for values in overrides.values() for key in values}
    for locale in UI_LOCALES:
        missing_overrides = override_keys - set(overrides.get(locale, {}))
        if missing_overrides:
            raise SystemExit(f"{locale} Android overrides missing: {sorted(missing_overrides)}")
    default_keys: set[str] | None = None
    for locale in UI_LOCALES:
        folder = "values" if locale == DEFAULT_LOCALE else f"values-{locale}"
        lproj = IOS_RESOURCES / f"{locale}.lproj"
        entries = parse_strings(lproj / "Localizable.strings")
        info = parse_strings(lproj / "InfoPlist.strings")
        # iOS `app.name` already maps to R.string.app_name (the launcher label).
        assert entries["app.name"] == info["CFBundleDisplayName"], locale
        entries["deck_document_type_name"] = info["UTTypeDescription"]
        plurals = load_plurals(lproj / "Localizable.stringsdict")
        # Android wording for copy that names Apple products or iOS UI.
        for key, value in overrides.get(locale, {}).items():
            if key not in entries:
                raise SystemExit(f"Android override for unknown iOS key: {key}")
            entries[key] = value
        if default_keys is None:
            default_keys = set(entries)
        missing = default_keys - set(entries)
        if missing:
            raise SystemExit(f"{locale} is missing {len(missing)} keys, e.g. {sorted(missing)[:5]}")
        outputs[ANDROID_RES / folder / OUTPUT_NAME] = render_strings(entries, plurals)
    learning = parse_strings(IOS_RESOURCES / "KoreanLearningContent.strings")
    learning = {LEARNING_PREFIX + key: value for key, value in learning.items()}
    outputs[ANDROID_RES / "values" / LEARNING_OUTPUT_NAME] = render_strings(learning, {}, translatable=False)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in render_all().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("Stale Android strings: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
